# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Kubecost Blog
logo: "/assets/images/kubecost-mark.png"
subtitle: "New Kubecost features and the latest in Kubernetes technology."
email:
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
twitter_username: username
github_username: kubecost
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: America/Los_Angeles # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
future: false

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-129422090-2"

author:
  name   : "Written by Kubecost"
  avatar : "/assets/images/kubecost-mark.png"
  bio    : "" # Empty bio string helps with spacing
  links:
    - label: "kubecost.com"
      icon: "fas fa-fw fa-link"
      url: "https://kubecost.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/kubecost"

footer:
  links:
    - label: "kubecost.com"
      icon: "fas fa-fw fa-link"
      url: "https://kubecost.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/"

defaults:
  # _posts
  - scope:
      path: ""
    values:
      # This sets additional sidebar content for _all_ pages. This is a great
      # way to get a "what is Kubecost?" blurb on all pages without being too
      # intrusive.
      # See: https://mmistakes.github.io/minimal-mistakes/docs/layouts/#custom-sidebar-content
      sidebar:
        -
          # title: "What is Kubecost?"
          text: >
            Kubecost is a cost monitoring and management tool for Kubernetes. We help our users track and save on billions of dollars of spend. Kubecost runs anywhere K8s runs; [install today](https://kubecost.com/install)!

  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
